import 'package:easily/models/user_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class GigModel {
/*
{
  "images": [
    ""
  ],
  "title": "",
  "description": "",
  "location": "",
  "baseAmount": 1.1,
  "impData": "",
  "createdAt": "",
  "showPhoneNumber": "",
  "deadline": "",
  "city": "",
  "tags": [
    ""
  ],
  "type": "",
  "createdBy": {},
  "acceptedBy": {},
  "completedAt": "",
  "paymentDone": false
} 
*/
  String? id;
  List<String?>? images;
  List<String?>? viewedBy;//list of ids of people who have viewed this gig
  int? viewedNos;//number of people who have viewed this gig
  String? title;
  String? description;
  String? location;
  bool? isRemote;
  double? baseAmount;
  String? impData;
  String? createdAt;
  String? showPhoneNumber;
  String? deadline;
  String? city;
  List<String?>? tags;
  String? type;
  UserModel? createdBy;
  UserModel? acceptedBy;
  String? completedAt;
  bool? paymentDone;
  String? imagesId;

  GigModel({
    this.id,
    this.viewedBy,
    this.viewedNos,
    this.images,
    this.imagesId,
    this.isRemote,
    this.title,
    this.description,
    this.location,
    this.baseAmount,
    this.impData,
    this.createdAt,
    this.showPhoneNumber,
    this.deadline,
    this.city,
    this.tags,
    this.type,
    this.createdBy,
    this.acceptedBy,
    this.completedAt,
    this.paymentDone,
  });
  GigModel.fromJson(Map<String, dynamic> json) {
    if (json['images'] != null && (json['images'] is List)) {
      final v = json['images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
        if (json['viewedBy'] != null && (json['viewedBy'] is List)) {
      final v = json['viewedBy'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      viewedBy = arr0;
    }
    title = json['title']?.toString();
    imagesId = json['imagesId']?.toString();
    id = json['_id']?.toString();
    isRemote = json['isRemote'];
    viewedNos = int.tryParse(json['viewedNos']?.toString() ?? '');

    description = json['description']?.toString();
    location = json['location']?.toString();
    baseAmount = double.tryParse(json['baseAmount']?.toString() ?? '');
    impData = json['impData']?.toString();
    createdAt = json['createdAt']?.toString();
    showPhoneNumber = json['showPhoneNumber']?.toString();
    deadline = json['deadline']?.toString();
    city = json['city']?.toString();
    if (json['tags'] != null && (json['tags'] is List)) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    type = json['type']?.toString();
    createdBy = (json['createdBy'] != null && (json['createdBy'] is Map))
        ? UserModel.fromJson(json['createdBy'])
        : null;
    acceptedBy = (json['acceptedBy'] != null && (json['acceptedBy'] is Map))
        ? UserModel.fromJson(json['acceptedBy'])
        : null;
    completedAt = json['completedAt']?.toString();
    paymentDone = json['paymentDone'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (images != null) {
      final v = images;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['images'] = arr0;
    }
        if (viewedBy != null) {
      final v = viewedBy;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['viewedBy'] = arr0;
    }
    data['title'] = title;
    data['imagesId'] = imagesId;
    data['isRemote'] = isRemote;
    data['viewedNos'] = viewedNos;

    data['description'] = description;
    data['location'] = location;
    data['baseAmount'] = baseAmount;
    data['impData'] = impData;
    data['createdAt'] = createdAt;
    data['showPhoneNumber'] = showPhoneNumber;
    data['deadline'] = deadline;
    data['city'] = city;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['tags'] = arr0;
    }
    data['type'] = type;
    if (createdBy != null) {
      data['createdBy'] = createdBy!.toJson();
    }
    if (acceptedBy != null) {
      data['acceptedBy'] = acceptedBy!.toJson();
    }
    data['completedAt'] = completedAt;
    data['paymentDone'] = paymentDone;
    return data;
  }
}
