///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReviewModel {
/*
{
  "receiverId": "",
  "username": "",
  "userid": "",
  "date": "",
  "review": 2.4,
  "title": "",
  "desc": "",
  "likes": [
    ""
  ],
  "likesNum": 0,
  "reported": true
} 
*/

  String? receiverId;
  String? username;
  String? userid;
  String? date;
  double? review;
  String? title;
  String? desc;
  List<String?>? likes;
  int? likesNum;
  bool? reported;

  ReviewModel({
    this.receiverId,
    this.username,
    this.userid,
    this.date,
    this.review,
    this.title,
    this.desc,
    this.likes,
    this.likesNum,
    this.reported,
  });
  ReviewModel.fromJson(Map<String, dynamic> json) {
    receiverId = json['receiverId']?.toString();
    username = json['username']?.toString();
    userid = json['userid']?.toString();
    date = json['date']?.toString();
    review = double.tryParse(json['review']?.toString() ?? '');
    title = json['title']?.toString();
    desc = json['desc']?.toString();
  if (json['likes'] != null && (json['likes'] is List)) {
  final v = json['likes'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    likes = arr0;
    }
    likesNum = int.tryParse(json['likesNum']?.toString() ?? '');
    reported = json['reported'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['receiverId'] = receiverId;
    data['username'] = username;
    data['userid'] = userid;
    data['date'] = date;
    data['review'] = review;
    data['title'] = title;
    data['desc'] = desc;
    if (likes != null) {
      final v = likes;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['likes'] = arr0;
    }
    data['likesNum'] = likesNum;
    data['reported'] = reported;
    return data;
  }
}

