import 'package:hive/hive.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
part 'user_model.g.dart';

@HiveType(typeId: 0)
class UserModel {
/*
{
  "id": "",
  "username": "",
  "fullname": "",
  "img": "",
  "email": "",
  "rating": 0,
  "numberOfRatings": 0,
  "phoneNumber": "",
  "joinedOn": "",
  "superuser": false
} 
*/
  @HiveField(0)
  String? id;
  @HiveField(1)
  String? username;
  @HiveField(2)
  String? fullname;
  @HiveField(3)
  String? img;
  @HiveField(4)
  String? email;
  @HiveField(5)
  int? rating;
  @HiveField(6)
  int? numberOfRatings;
  @HiveField(7)
  String? phoneNumber;
  @HiveField(8)
  String? joinedOn;
  @HiveField(9)
  bool? superuser;
  @HiveField(10)
  List<String?>? reviews;
  @HiveField(11)
  String? cityToSearch;
  @HiveField(12)
  String? token;

  UserModel({
    this.token,
    this.id,
    this.username,
    this.fullname,
    this.img,
    this.email,
    this.cityToSearch,
    this.rating,
    this.numberOfRatings,
    this.reviews,
    this.phoneNumber,
    this.joinedOn,
    this.superuser,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    if (json['reviews'] != null && (json['reviews'] is List)) {
      final v = json['reviews'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      reviews = arr0;
    }
    id = json['id']?.toString();
    cityToSearch = json['cityToSearch']?.toString();
    token = json['token']?.toString();

    username = json['username']?.toString();
    fullname = json['fullname']?.toString();
    img = json['img']?.toString();
    email = json['email']?.toString();
    rating = int.tryParse(json['rating']?.toString() ?? '');
    numberOfRatings = int.tryParse(json['numberOfRatings']?.toString() ?? '');
    phoneNumber = json['phoneNumber']?.toString();
    joinedOn = json['joinedOn']?.toString();
    superuser = json['superuser'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['fullname'] = fullname;
    data['token'] = token;
    if (reviews != null) {
      final v = reviews;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['reviews'] = arr0;
    }
    data['img'] = img;
    data['cityToSearch'] = cityToSearch;

    data['email'] = email;
    data['rating'] = rating;
    data['numberOfRatings'] = numberOfRatings;
    data['phoneNumber'] = phoneNumber;
    data['joinedOn'] = joinedOn;
    data['superuser'] = superuser;
    return data;
  }
}
