// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32ZfDoNlcZzGro5Qg2wCBzmSj-3P_yJ4',
    appId: '1:647260009941:web:4cbf3b9badb5dd3c08395c',
    messagingSenderId: '647260009941',
    projectId: 'getitdoneeasily',
    authDomain: 'getitdoneeasily.firebaseapp.com',
    storageBucket: 'getitdoneeasily.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCVfP3D4IKK5gH3GhiCeB1zqTRHGs9zI',
    appId: '1:647260009941:android:994db48f94a92fe908395c',
    messagingSenderId: '647260009941',
    projectId: 'getitdoneeasily',
    storageBucket: 'getitdoneeasily.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeyN6_KgyxB0ZWFR0BJsQnJGlaDyHuwWE',
    appId: '1:647260009941:ios:a73f3445e3eb1a3a08395c',
    messagingSenderId: '647260009941',
    projectId: 'getitdoneeasily',
    storageBucket: 'getitdoneeasily.appspot.com',
    iosClientId:
        '647260009941-ldg0okn9h70ghv80j73k06octtu7ine4.apps.googleusercontent.com',
    iosBundleId: 'com.example.easily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeyN6_KgyxB0ZWFR0BJsQnJGlaDyHuwWE',
    appId: '1:647260009941:ios:a73f3445e3eb1a3a08395c',
    messagingSenderId: '647260009941',
    projectId: 'getitdoneeasily',
    storageBucket: 'getitdoneeasily.appspot.com',
    iosClientId:
        '647260009941-ldg0okn9h70ghv80j73k06octtu7ine4.apps.googleusercontent.com',
    iosBundleId: 'com.example.easily',
  );
}
